services:
  rest-api:
    depends_on:
      - database
    build:
        context: ../../
        dockerfile: src/docker/Dockerfile
    ports:
        - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/sb_users
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
  database:
    image: postgres:16-alpine
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: sb_users
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
